### PR TITLE
Code clearing (+ small fixes/refactoring), using iron-demo-helpers component

### PR DESCRIPTION
**Pull request by teslor**
Demo page was redone using iron-demo-helpers element (recommended element to create demo pages).
At present demo-snippet element doesn't show source code (because of this issue - https://github.com/PolymerElements/iron-demo-helpers/issues/29).
Hope this issue will be fixed soon (or I'll find workaround). Anyway it provides good looking Polymer style demo page.

### CODE REVIEW

**Comment by plequang** [comment]
Using `<demo-snippet>` is a good idea.
If you want to have `<demo-snippet>` to work correctly, you have to change a bit how the demo is implemented. 
As explained in the issue you mentionned, `<demo-snippet>` does not work when it is inside a `dom-bind` template or another element template.
What works though is to use a dom-bind template inside the demo-snippet :
```html
<div class="vertical-section-container">
  <h3>Multi selection selected items</h3>
  <demo-snippet>
    <template is="dom-bind" id="t1">
      <cosmoz-autocomplete selected-items="{{ demoSelected1 }}" items="{{ demoItems }}"
                  placeholder="Search">
      </cosmoz-autocomplete>
    </template>
  </demo-snippet>
</div>
```
In the script, you have to get this template and assign the necessary bindings:

```js
var t1 = document.querySelector('#t1');
t1.demoItems = ...
```

(The `demo-page` element must be removed).

**Comment by teslor** [comment]
Yeah, I also thought about removing demo-page to avoid template , but decided to do this variant for a start. Thanks.

**Comment by teslor** [comment]
Switched to <template is="dom-bind">. However not everything works correctly:
1) data binding attridutes inside cosmoz-autocomplete are cut off in source code.
2) copy to clipboard doesn't work
So, it's not a finished version & additional checks are needed.

**Comment by plequang** [comment]
Looks very nice.
I think attributes are removed in source code because you referenced iron-demo-helpers version 2.x
Same for copy to clipboard. 
Would it be possible to increase the "boxes" width, so that one do not need to scroll too much in the source snippet ?

**Comment by teslor** [comment]
You are right, 1st version doesn't have such problems, I supposed 2.x should work correctly with both Polymer 1 & 2 elements.

**Pull request merged**
