### PR TITLE
Some unnecessary code removed

### PR DESCRIPTION
**Pull request by teslor**

### CODE REVIEW

**Comment by teslor** [comment]
Addition:
I removed only function expression & "window.Cosmoz = window.Cosmoz || {};" line. Because of removing function expression the all code is shifted to left.

**Comment by plequang** [comment]
Hi,
We can't get rid of the function wrapper around the element definition.
We want to use "strict mode", but we can't impose other component providers to use it. So having a "use strict" statement might break code when we run a concatenated (vulcanized) version of our application. The "function form" of "use strict" does not have any side effect when the scripts are concatenated.

Concerning the `Cosmoz` namespace.
As recommended by Polymer, we use this  namespace to register our behaviors.
> Behaviors created by the Polymer team are added to the Polymer object. When creating your own behaviors, you should use some other namespace to avoid collisions with future Polymer behaviors.
https://www.polymer-project.org/1.0/docs/devguide/behaviors#defining-behaviors

It's true that we don't need this namespace for `cosmoz-autocomplete`  as it does not create a behavior. However, we would like to have a safe/unified/standardized "skeleton" for all our scripts that should look like:
```
(function () {
	'use strict';
	window.Cosmoz = window.Cosmoz || {};
```

**Comment by teslor** [comment]
Yes, I removed Cosmoz because the namespace should be set only in behavior element. "window.Cosmoz = window.Cosmoz || {}" just do nothing here, because if behavior is not imported the element won't work correctly in any case.
About 'use strict' - understood. By the way 'use strict' is a bit legacy. At present it's less used.
Thanks.

**Comment by nomego** [comment]
I'm closing this, but the `window.Cosmoz` comments are valid.
Maybe we should consider throwing an error if the namespace is undefined for non-behavior-providing components.

`'use strict'` is not legacy, it's just becoming more and more mandatory in things like ES6 modules, but there's no really good reason to stop complying.

**Pull request closed without merging**
